// <auto-generated />
using System;
using Goron_Melisa_Proiect_Medii.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Goron_Melisa_Proiect_Medii.Migrations
{
    [DbContext(typeof(Goron_Melisa_Proiect_MediiContext))]
    [Migration("20210106161336_ClasaID")]
    partial class ClasaID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.Clasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeClasa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clasa");
                });

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeDisciplina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.Tema", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClasaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Elev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titlu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClasaID");

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.TemaDisciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<int>("TemaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("TemaID");

                    b.ToTable("TemaDisciplina");
                });

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.Tema", b =>
                {
                    b.HasOne("Goron_Melisa_Proiect_Medii.Models.Clasa", "Clasa")
                        .WithMany("Teme")
                        .HasForeignKey("ClasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Goron_Melisa_Proiect_Medii.Models.TemaDisciplina", b =>
                {
                    b.HasOne("Goron_Melisa_Proiect_Medii.Models.Disciplina", "Disciplina")
                        .WithMany("TemaDiscipline")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goron_Melisa_Proiect_Medii.Models.Tema", "Tema")
                        .WithMany("TemaDiscipline")
                        .HasForeignKey("TemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
